[build]
  # Build command for Next.js with API routes
  command = "npm install && npm run build"
  
  # Publish directory
  publish = ".next"

[build.environment]
  # Node.js version
  NODE_VERSION = "18"
  
  # Next.js environment
  NEXT_TELEMETRY_DISABLED = "1"
  
  # Build environment
  NODE_ENV = "production"

# Redirect rules for Next.js
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Fallback for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache headers for static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# API routes configuration
[functions]
  # Enable Netlify Functions for API routes
  directory = ".netlify/functions"

# Build plugins
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Environment variables (these should be set in Netlify dashboard)
# PESAPAL_CONSUMER_KEY = "x8Laqe3NN5ZwIMFFeQgd4lwSJhHwwDXL"
# PESAPAL_CONSUMER_SECRET = "Q9twNwMHt8a03lFfODhnteP9fnY="
# NEXT_PUBLIC_PESAPAL_BASE_URL = "https://cybqa.pesapal.com/pesapalv3/api"