[build]
  # Build command for Next.js with error handling
  command = "npm ci && npm run build"
  
  # Directory to publish (Next.js static export)
  publish = "out"

[build.environment]
  # Node.js version
  NODE_VERSION = "20"
  
  # Next.js environment
  NEXT_TELEMETRY_DISABLED = "1"
  
  # Disable ESLint during build
  ESLINT_NO_DEV_ERRORS = "true"
  
  # Skip type checking during build
  SKIP_TYPE_CHECK = "true"

# Redirect rules for SPA routing (for static export)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Pesapal API redirects
[[redirects]]
  from = "/api/pesapal/stk-push"
  to = "/.netlify/functions/stk-push"
  status = 200

# Pesapal callback redirects
[[redirects]]
  from = "/pesapal/callback"
  to = "/.netlify/functions/pesapal-callback"
  status = 200

[[redirects]]
  from = "/pesapal/ipn"
  to = "/.netlify/functions/pesapal-ipn"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https://*.pesapal.com;"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Environment variables (these will be set in Netlify dashboard)
# NEXT_PUBLIC_PESAPAL_BASE_URL
# NEXT_PUBLIC_PESAPAL_CONSUMER_KEY
# PESAPAL_CONSUMER_SECRET
# NEXT_PUBLIC_SITE_URL